AutorenProjekt2/Controllers/BuchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutorenProjekt2.Data;
using AutorenProjekt2.Models;

namespace AutorenProjekt2.Controllers
{
    public class BuchController : Controller
    {
        private readonly AutorenProjekt2Context _context;

        public BuchController(AutorenProjekt2Context context)
        {
            _context = context;
        }

        // GET: Buch
        public async Task<IActionResult> Index()
        {
            return View(await _context.Buch.ToListAsync());
        }

        // GET: Buch/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buch = await _context.Buch
                .FirstOrDefaultAsync(m => m.Id == id);
            if (buch == null)
            {
                return NotFound();
            }

            return View(buch);
        }

        //// GET: Buch/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Buch/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,Buchtitel,Klappentext,Preis,Erscheinungsdatum,ISBN,BuchCover")] Buch buch)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(buch);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(buch);
        //}

        //// GET: Buch/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var buch = await _context.Buch.FindAsync(id);
        //    if (buch == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(buch);
        //}

        //// POST: Buch/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,Buchtitel,Klappentext,Preis,Erscheinungsdatum,ISBN,BuchCover")] Buch buch)
        //{
        //    if (id != buch.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(buch);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!BuchExists(buch.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(buch);
        //}

        //// GET: Buch/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var buch = await _context.Buch
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (buch == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(buch);
        //}

        //// POST: Buch/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var buch = await _context.Buch.FindAsync(id);
        //    if (buch != null)
        //    {
        //        _context.Buch.Remove(buch);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool BuchExists(int id)
        {
            return _context.Buch.Any(e => e.Id == id);
        }
    }
}

AutorenProjekt2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    @* <title>@ViewData["Title"] - AutorenProjekt2</title> *@
    <title>Adeline Meadows</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant:ital,wght@0,300..700;1,300..700&family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AutorenProjekt2.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="~/css/style.css" media="screen">
</head>
<body>
    <header>
          <div class="header">
            <h1 class="headline">Adeline Meadows</h1>
            <h2 class="subtitle">Autorin</h2>
        </div>  
    </header>

    <div id="navi">
            <ul>
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Startseite</a> </li>
                 @* <li><a asp-area="" asp-controller="Rezension" asp-action="BuchRezension">BuchRezension</a> </li> *@
                 <li> <a asp-area="" asp-controller="Buch" asp-action="Index">Bücher</a> </li>
                @* <li><a asp-area="" asp-controller="Rezension" asp-action="Index">Rezension</a> </li> *@
                 <li><a asp-area="" asp-controller="Home" asp-action="UberMich">Über Mich</a> </li>
                <li><a asp-area="" asp-controller="Home" asp-action="Kontakt">Kontakt</a> </li>          
            </ul>
     </div>
       
    
    <div class="container">
        <main role="main" class="Startseite-background">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="footer-Container">
            <div class="social-Icons">
                <a href="#" title="Facebook"><i class="fa fa-facebook"></i></a>
                <a href="#" title="Instagram"><i class="fa fa-instagram"></i></a>
                <a href="#" title="Twitter"><i class="fa fa-twitter"></i></a>
                <a href="#" title="Youtube"><i class="fa  fa-youtube"></i></a>
            </div>
            <div class="footerNav">
                <ul>
                    <li><a asp-area="" asp-controller="Home" asp-action="Kontakt">Kontakt</a> </li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Impressum">Impressum</a> </li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Datenschutz">Datenschutz</a> </li>
                    <li><a href="#navi" title="nach Oben">nach Oben</a></li>
                </ul>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>